using System.Collections.Generic;
using System;
using Terraria;
using Terraria.ID;

/// <summary>
/// InventoryState represents the state of an inventory at a specific moment.
/// 
/// DESIGN EXPLANATION:
/// -------------------
/// This class is **optimized for detecting stack size increases** and **new item appearances** between two inventory states.
/// 
/// We specifically care about:
/// - Total stack size per item type across all slots.
/// - Detecting if an item has increased in total stack size compared to a previous state.
/// - Detecting if a completely new item type appeared (was not present before).
///
/// We deliberately **ignore**:
/// - Exact slot positions (we don't care which slot an item is in).
/// - Stack splitting (we don't care if items split across multiple slots).
/// - Stack size decreases (we don't care if a player consumes/drops items).
/// - Complete removal of items (we only track positive changes).
///
/// WHY THIS DESIGN:
/// ----------------
/// - We only need **per item type totals**, not detailed per-slot info.
/// - Storing full slot-by-slot information would waste memory and slow down comparisons.
/// - A single Dictionary<string, ItemInfo> allows O(1) lookup, O(n) total construction and comparison.
/// - This keeps the InventoryState extremely lightweight, fast to build, and fast to compare.
///
/// FINAL ARCHITECTURE:
/// -------------------
/// - One record: ItemInfo (Item type + total stack size).
/// - One dictionary: maps item type (string) to ItemInfo.
/// - CompareTo() returns a list of ChangeResult containing only positive changes (type + increase).
///
/// USAGE:
/// ------
/// - Build InventoryState from a List<Item?> (inventory slots).
/// - Call CompareTo(previousState) to detect stack size increases and new items.
/// - Use the resulting List<ChangeResult> for tracking player progression, inventory gains, etc.
/// </summary>
// docs generated by AI
// @TODO: add slots for ammo and coins
public class InventoryState
{
    private readonly Dictionary<int, int> _inventoryMap = new();

    public InventoryState(Item[] inventory)
    {
        BuildInventoryMap(inventory);
    }

    private void BuildInventoryMap(Item[] inventory)
    {
        foreach (var item in inventory)
        {
            if (item != null && item.stack > 0 && item.type != ItemID.None)
            {
                if (_inventoryMap.TryGetValue(item.type, out var existingStack))
                {
                    _inventoryMap[item.type] = existingStack + item.stack;
                }
                else
                {
                    _inventoryMap[item.type] = item.stack;
                }
            }
        }
    }
    public Dictionary<int,int> GetInventoryMap() => _inventoryMap;

    public List<(int itemType, int amountPickedUp)> CompareTo(InventoryState previous)
    {
        var previousMap = previous._inventoryMap;
        var changes = new List<(int itemType, int amountPickedUp)>();

        foreach (var (type, currentTotal) in _inventoryMap)
        {
            if (!previousMap.TryGetValue(type, out var previousTotal))
            {
                // New item
                changes.Add((type, currentTotal));
            }
            else
            {
                int diff = currentTotal - previousTotal;
                if (diff > 0)
                {
                    changes.Add((type, diff));
                }
            }
        }

        return changes;
    }
}
